import { type SceneProcedureStep } from "@/labs/experiments/types";

export const step: SceneProcedureStep = {
  label: "Wire the adder inputs",
  body: "Connect $A_1$–$A_4$ from the A switches (row a, cols 1–4) directly to the adder A inputs with orange wires — these bypass the inverters. Tie the carry-in $C_0$ (col 19 row e) to the +5 V rail with a red wire. $C_0 = 1$ adds the extra +1 of the 2's complement, so the adder now computes $A + \\overline{B} + 1 = A - B$.",
  show: [
    "bb",
    "xor_b1",
    "xor_b2",
    "xor_b3",
    "xor_b4",
    "w_vcc_xb1",
    "w_vcc_xb2",
    "w_vcc_xb3",
    "w_vcc_xb4",
    "adder_sub",
    "w_c0_vcc",
    "w_a1_adder_sub",
    "w_a2_adder_sub",
    "w_a3_adder_sub",
    "w_a4_adder_sub",
    "w_b1_xor",
    "w_b2_xor",
    "w_b3_xor",
    "w_b4_xor",
    "w_xb1_adder",
    "w_xb2_adder",
    "w_xb3_adder",
    "w_xb4_adder",
  ],
  highlight: "w_c0_vcc",
};
