import { type SceneProcedureStep } from "@/labs/experiments/types";

export const step: SceneProcedureStep = {
  label: "Test a case with borrow",
  body: "Set $A = 0101$ (5) and $B = 1001$ (9). The carry-out $C_4$ LED is OFF ($C_4 = 0$), so Borrow $= \\overline{C_4} = 1$ and $A < B$. The sum LEDs read $1100$, which is the 2's complement of the magnitude: $\\overline{1100} + 1 = 0100 = 4$, so $A - B = -4$. Repeat for $3 - 8$.",
  show: [
    "bb",
    "xor_b1",
    "xor_b2",
    "xor_b3",
    "xor_b4",
    "w_vcc_xb1",
    "w_vcc_xb2",
    "w_vcc_xb3",
    "w_vcc_xb4",
    "adder_sub",
    "w_c0_vcc",
    "w_a1_adder_sub",
    "w_a2_adder_sub",
    "w_a3_adder_sub",
    "w_a4_adder_sub",
    "w_b1_xor",
    "w_b2_xor",
    "w_b3_xor",
    "w_b4_xor",
    "w_xb1_adder",
    "w_xb2_adder",
    "w_xb3_adder",
    "w_xb4_adder",
    "r_s1",
    "r_s2",
    "r_s3",
    "r_s4",
    "r_c4",
    "led_s1",
    "led_s2",
    "led_s3",
    "led_s4",
    "led_c4",
    "w_s1_r",
    "w_s1_led",
    "w_s1_gnd",
    "w_s2_r",
    "w_s2_led",
    "w_s2_gnd",
    "w_s3_r",
    "w_s3_led",
    "w_s3_gnd",
    "w_s4_r",
    "w_s4_led",
    "w_s4_gnd",
    "w_c4_r",
    "w_c4_led",
    "w_c4_gnd",
  ],
  highlight: "led_c4",
  supplyVoltage: 5.0,
  activeInputs: { A4: 0, A3: 1, A2: 0, A1: 1, B4: 1, B3: 0, B2: 0, B1: 1 },
};
