import { type SceneProcedureStep } from "@/labs/experiments/types";

export const step: SceneProcedureStep = {
  label: "Connect the slave stage",
  body: "Connect the master-stage state to the slave-stage input logic, then cross-couple the slave NAND outputs to form the stored output state.",
  show: [
    "bb",
    "psu",
    "bb2",
    "nand1",
    "nand2",
    "nand3",
    "not_d",
    "nand4",
    "nand5",
    "nand6",
    "not_clk",
    "w_d_not",
    "w_d_master",
    "w_clk_not",
    "w_clk_master",
    "w_clkbar_master",
    "w_notd_master",
    "w_master_set",
    "w_master_reset",
    "w_master_fb1",
    "w_master_fb2",
    "w_slave_in1",
    "w_slave_in2",
    "w_slave_fb1",
    "w_slave_fb2",
  ],
  highlight: "w_slave_in1",
  activeInputs: { D: 0, CLK: 0 },
};
