import { type SceneProcedureStep } from "@/labs/experiments/types";

export const step: SceneProcedureStep = {
  label: "Verify output retention",
  body: "After a rising edge, change D without producing another rising edge. Q must remain at the previously stored value. This confirms that the circuit stores data between active clock edges.",
  show: [
    "bb",
    "psu",
    "bb2",
    "nand1",
    "nand2",
    "nand3",
    "not_d",
    "nand4",
    "nand5",
    "nand6",
    "not_clk",
    "w_d_not",
    "w_d_master",
    "w_clk_not",
    "w_clk_master",
    "w_clkbar_master",
    "w_notd_master",
    "w_master_set",
    "w_master_reset",
    "w_master_fb1",
    "w_master_fb2",
    "w_slave_in1",
    "w_slave_in2",
    "w_slave_fb1",
    "w_slave_fb2",
    "r_q",
    "r_qb",
    "led_q",
    "led_qb",
    "w_q_r",
    "w_r_led_q",
    "w_qb_r",
    "w_r_led_qb",
    "w_gnd_q",
    "w_gnd_qb",
  ],
  highlight: "led_q",
  activeInputs: { D: 1, CLK: 0 },
  supplyVoltage: 5.0,
  ledBrightness: { led_q: 1, led_qb: 0 },
};
