import { type SceneProcedureStep } from "@/labs/experiments/types";

export const step: SceneProcedureStep = {
  label: "Test all four input combinations.",
  body: "The circuit is complete. Set A = 0 and B = 1: the green (Sum/Difference) LED and the red (Borrow) LED turn ON while the yellow (Carry) LED stays OFF. Now try the other combinations with the input panel and fill the observation table.",
  show: [
    "bb",
    "psu",
    "w_rail_link",
    "xor1",
    "and1",
    "w_vcc_xor1",
    "w_gnd_xor1",
    "w_vcc_and1",
    "w_gnd_and1",
    "not1",
    "and2",
    "w_vcc_not1",
    "w_gnd_not1",
    "w_vcc_and2",
    "w_gnd_and2",
    "w_a_xor",
    "w_a_and",
    "w_a_not",
    "w_b_xor",
    "w_b_and",
    "w_b_and2",
    "w_not_and2",
    "r_sd",
    "led_sd",
    "r_c",
    "led_c",
    "r_b",
    "led_b",
    "w_xor_r",
    "w_r_led_sd",
    "w_and_r",
    "w_r_led_c",
    "w_and2_r",
    "w_r_led_b",
    "w_gnd_sd",
    "w_gnd_c",
    "w_gnd_b",
  ],
  activeInputs: { A: 0, B: 1 },
  ledBrightness: { led_sd: 1, led_c: 0, led_b: 1 },
  audioPath: "/semesters/semester-02/01-digital-electronics/half-adder-subtractor/04-procedure/10-procedure.mp3",
};
