import { type SceneProcedureStep } from "@/labs/experiments/types";

export const step: SceneProcedureStep = {
  label: "Verify the two-level network.",
  body: "Apply $A = 1$, $B = 1$, $C = 0$. The first AND gate gives $AB = 1$, so the OR gate output is 1 and the green LED glows. Now try all eight input combinations and record $F_1$ in the observation table. $F_1$ should be 1 only for $ABC$ = 101, 110 and 111.",
  show: [
    "bb",
    "psu",
    "w_rail_link_vcc",
    "w_rail_link_gnd",
    "and1",
    "and2",
    "or1",
    "w_vcc_and1",
    "w_gnd_and1",
    "w_vcc_and2",
    "w_gnd_and2",
    "w_vcc_or1",
    "w_gnd_or1",
    "w_a_and1",
    "w_b_and1",
    "w_a_and2",
    "w_c_and2",
    "w_and1_or1",
    "w_and2_or1",
    "r_f1",
    "led_f1",
    "w_or1_r",
    "w_r_led_f1",
    "w_gnd1",
  ],
  highlight: "led_f1",
  activeInputs: { A: 1, B: 1, C: 0 },
  ledBrightness: { led_f1: 1 },
};
