import { type SceneProcedureStep } from "@/labs/experiments/types";

export const step: SceneProcedureStep = {
  label: "Wire the factored network.",
  body: "Connect inputs $B$ (blue) and $C$ (orange) to the two inputs of the new OR gate. Connect the OR output to the B pin of the new AND gate with a white wire, and connect input $A$ (red) to the A pin of the AND gate. The OR gate output is the intermediate term $B + C$.",
  show: [
    "bb",
    "psu",
    "w_rail_link_vcc",
    "w_rail_link_gnd",
    "and1",
    "and2",
    "or1",
    "w_vcc_and1",
    "w_gnd_and1",
    "w_vcc_and2",
    "w_gnd_and2",
    "w_vcc_or1",
    "w_gnd_or1",
    "w_a_and1",
    "w_b_and1",
    "w_a_and2",
    "w_c_and2",
    "w_and1_or1",
    "w_and2_or1",
    "r_f1",
    "led_f1",
    "w_or1_r",
    "w_r_led_f1",
    "w_gnd1",
    "or2",
    "and3",
    "w_vcc_or2",
    "w_gnd_or2",
    "w_vcc_and3",
    "w_gnd_and3",
    "w_b_or2",
    "w_c_or2",
    "w_or2_and3",
    "w_a_and3",
  ],
  highlight: "w_or2_and3",
  activeInputs: { A: 0, B: 0, C: 0 },
  ledBrightness: { led_f1: 0 },
};
