import { type SceneProcedureStep } from "@/labs/experiments/types";

export const step: SceneProcedureStep = {
  label: "Connect the F2 indicator.",
  body: "Take the output of the second AND gate through a $330\\,\\Omega$ resistor to the yellow LED and return the LED cathode to ground. The yellow LED shows $F_2 = A(B + C)$.",
  show: [
    "bb",
    "psu",
    "w_rail_link_vcc",
    "w_rail_link_gnd",
    "and1",
    "and2",
    "or1",
    "w_vcc_and1",
    "w_gnd_and1",
    "w_vcc_and2",
    "w_gnd_and2",
    "w_vcc_or1",
    "w_gnd_or1",
    "w_a_and1",
    "w_b_and1",
    "w_a_and2",
    "w_c_and2",
    "w_and1_or1",
    "w_and2_or1",
    "r_f1",
    "led_f1",
    "w_or1_r",
    "w_r_led_f1",
    "w_gnd1",
    "or2",
    "and3",
    "w_vcc_or2",
    "w_gnd_or2",
    "w_vcc_and3",
    "w_gnd_and3",
    "w_b_or2",
    "w_c_or2",
    "w_or2_and3",
    "w_a_and3",
    "r_f2",
    "led_f2",
    "w_and3_r",
    "w_r_led_f2",
    "w_gnd2",
  ],
  highlight: "led_f2",
  activeInputs: { A: 0, B: 0, C: 0 },
  ledBrightness: { led_f1: 0, led_f2: 0 },
};
