import { type ExperimentDefinition } from "@/labs/experiments/types";

type Section = ExperimentDefinition["sections"][number];

export const theory: Section = {
  id: "theory",
  type: "text",
  title: "Theory",
  paragraphs: [
    "An operational amplifier (op-amp) is a high-gain, direct-coupled differential amplifier with two inputs and one output. The input marked minus is the inverting input and the input marked plus is the non-inverting input. The output voltage is Vo = A × (V+ − V−), where A is the open-loop gain. The LM741 used in this experiment is a general-purpose op-amp in an 8-pin DIP package. It needs a dual power supply: +12 V is applied to pin 7 and −12 V to pin 4, and the common (0 V) terminal of the supply is the ground of the circuit.",
    "LM741 pin connections (top view, notch at the top): pin 1 offset null, pin 2 inverting input (−), pin 3 non-inverting input (+), pin 4 negative supply V−, pin 5 offset null, pin 6 output, pin 7 positive supply V+, pin 8 no connection. Pins 1, 5 and 8 are left unconnected in this experiment.",
    "The open-loop gain of the LM741 is very large (typically about 200,000 at DC) but poorly controlled, so the op-amp is used with negative feedback in linear circuits. With negative feedback the closed-loop gain is set almost entirely by external resistors. For an ideal op-amp with negative feedback two rules apply. First, no current flows into either input terminal. Second, the voltage difference between the two input terminals is zero (V+ = V−), which is called the virtual short.",
    "Inverting amplifier. The input signal Vin is applied through the input resistor Rin to the inverting terminal (pin 2). The non-inverting terminal (pin 3) is connected to ground, and the feedback resistor Rf is connected between the output (pin 6) and the inverting terminal. Since V+ = 0 V, the virtual short makes the inverting terminal a virtual ground (V− ≈ 0 V). The current through Rin is Iin = Vin / Rin. No current enters the op-amp, so the same current flows through Rf and the output voltage is Vo = 0 − Iin × Rf. Therefore Vo = −(Rf / Rin) × Vin and the closed-loop voltage gain is Av = Vo / Vin = −Rf / Rin. The negative sign means that the output is 180° out of phase with the input. The input resistance seen by the source is equal to Rin.",
    "Non-inverting amplifier. The input signal Vin is applied directly to the non-inverting terminal (pin 3). The feedback resistor Rf is connected between the output (pin 6) and the inverting terminal (pin 2), and the resistor R1 is connected between the inverting terminal and ground. Rf and R1 form a voltage divider across the output, so V− = Vo × R1 / (R1 + Rf). The virtual short gives V− = V+ = Vin, therefore Vo = Vin × (R1 + Rf) / R1. The closed-loop voltage gain is Av = Vo / Vin = 1 + Rf / R1. This gain is positive and never less than 1, so the output is in phase with the input (0° phase shift). The input resistance is very high because the signal drives the op-amp input terminal directly. If Rf is replaced by a short circuit and R1 is removed, the gain becomes 1 and the circuit is a voltage follower (unity-gain buffer).",
    "Values used in this experiment. Rin = R1 = 10 kΩ and Rf is taken as 100 kΩ, 47 kΩ and 22 kΩ in turn. The theoretical gains are therefore −10, −4.7 and −2.2 for the inverting amplifier, and 11, 5.7 and 3.2 for the non-inverting amplifier. A sine wave of 1 kHz and 1 V peak-to-peak is applied at the input in every case.",
    "Practical limits. The output voltage cannot exceed the supply voltages. With ±12 V supplies the output of the LM741 saturates a volt or two below the supply rails, so the input amplitude must be small enough for the amplified peaks to stay below this level; this is why 1 V peak-to-peak is used. The gain-bandwidth product of the LM741 is about 1 MHz, so the −3 dB bandwidth of a closed-loop amplifier is roughly 1 MHz divided by its noise gain (1 + Rf / Rin for the inverting circuit and 1 + Rf / R1 for the non-inverting circuit). For a gain setting of 10 or 11 this is of the order of 100 kHz, which is well above the 1 kHz test frequency.",
  ],
};
