import Link from "next/link";
import {
  Prose,
  DocEyebrow,
  Callout,
  DocNav,
  DocNavLink,
} from "@/sections/docs/doc-primitives";

export const metadata = {
  title: "Docs — VLabs",
  description: "Overview of the VLabs lab system and how to extend it.",
};

export default function DocsIndexPage() {
  return (
    <Prose>
      <DocEyebrow>Documentation</DocEyebrow>
      <h1>VLabs — Lab System Overview</h1>

      <p>
        VLabs is a Next.js application for interactive 3D electronics education.
        The lab system supports multiple experiment modes and has two key layers
        you can extend independently:
      </p>

      <ul>
        <li>
          <strong>Experiment definitions</strong> — TypeScript data files
          organised into semesters and subjects. Each experiment contains a
          circuit definition, lab content (aim, theory, apparatus, procedure,
          observations, conclusion), and metadata. Designed to be generated by
          AI.
        </li>
        <li>
          <strong>Component builders</strong> — Three.js geometry functions that
          turn a component instance into a 3D mesh. Each component type lives in
          its own folder under <code>src/components/</code>.
        </li>
      </ul>

      <p>
        The renderer (<code>LabScene.tsx</code>) is fully data-driven through a
        <strong> component registry</strong> — a plain object that maps type
        strings to builder functions. Adding a new component type requires
        creating a new folder in <code>src/components/</code> and adding a
        registry entry.
      </p>

      <hr />

      <h2>How the pieces fit together</h2>

      <pre>{`src/
  components/                  ← shared physical component library (Three.js geometry)
    breadboard/                ← one folder per component type
    resistor/
    led/
    ic/
    diode/
    bjt/
    mosfet/
    op-amp/
    oscilloscope/
    ...28 component types
    shared/                    ← materials, primitives, helpers
    index.ts                   ← barrel export

  labs/
    types.ts                   ← ComponentInstance union + Circuit type
    lab-content.types.ts       ← LabContent, TheorySection, ApparatusSection, etc.
    LabScene.tsx               ← Renderer + COMPONENT_REGISTRY
    ApparatusScene.tsx         ← 3D apparatus viewer
    TheoryScene.tsx            ← 3D schematic overlay
    builder.ts                 ← CB fluent API for building circuits
    coords.ts                  ← hole() / railHole() coordinate helpers
    semesters/                 ← experiment catalog
      catalog.ts               ← SEMESTER_SUBJECTS master registry
      semester-01/
        01-analog-electronics/
          ohms-law/
            01-aim.ts
            02-theory.ts
            03-apparatus.ts
            04-procedure/
            05-observations.ts
            06-conclusion.ts
            components.ts      ← circuit definition
            index.ts           ← barrel export
          ...11 experiments
        02-computer-application/
        03-analog-electronics-advanced/
      semester-02/
      semester-03/
      semester-04/
    circuits/
      index.ts                 ← re-exports SEMESTER_CIRCUITS as ALL_CIRCUITS
    experiments/
      types.ts                 ← ExperimentDefinition type
      build.ts                 ← experiment building helpers`}</pre>

      <h2>Lab modes</h2>

      <p>
        Experiments can use different rendering modes via the{" "}
        <code>labType</code> field:
      </p>

      <table>
        <thead>
          <tr>
            <th>Mode</th>
            <th>Description</th>
          </tr>
        </thead>
        <tbody>
          <tr>
            <td>
              <code>&apos;breadboard&apos;</code>
            </td>
            <td>Interactive 3D breadboard scene (default)</td>
          </tr>
          <tr>
            <td>
              <code>&apos;text&apos;</code>
            </td>
            <td>Theory/text-only lab — no 3D scene</td>
          </tr>
          <tr>
            <td>
              <code>&apos;code&apos;</code>
            </td>
            <td>Code editor / programming lab (e.g. 8085 assembly)</td>
          </tr>
          <tr>
            <td>
              <code>&apos;simulation&apos;</code>
            </td>
            <td>Circuit simulation without physical breadboard</td>
          </tr>
        </tbody>
      </table>

      <h2>Quick orientation</h2>

      <table>
        <thead>
          <tr>
            <th>Task</th>
            <th>Files to edit</th>
          </tr>
        </thead>
        <tbody>
          <tr>
            <td>
              Add a new <strong>experiment</strong>
            </td>
            <td>
              <code>semesters/&lt;sem&gt;/&lt;subject&gt;/&lt;name&gt;/</code>{" "}
              (new folder with aim, theory, apparatus, procedure, observations,
              conclusion, components, index) + <code>semesters/catalog.ts</code>
            </td>
          </tr>
          <tr>
            <td>
              Add a new <strong>component type</strong> (new physical part)
            </td>
            <td>
              <code>src/components/&lt;name&gt;/</code> (new folder) +{" "}
              <code>src/components/index.ts</code> + <code>LabScene.tsx</code>{" "}
              (one registry entry)
            </td>
          </tr>
          <tr>
            <td>
              Add a new <strong>circuit</strong> (new wiring of existing parts)
            </td>
            <td>
              Create <code>components.ts</code> in the experiment folder using{" "}
              the <code>CB</code> builder or manual <code>Circuit</code> object
            </td>
          </tr>
          <tr>
            <td>Generate an experiment with AI</td>
            <td>
              Paste <code>src/labs/COMPONENTS.md</code> into Claude, prompt,
              save output into the experiment folder structure
            </td>
          </tr>
        </tbody>
      </table>

      <Callout $tone="tip">
        <strong>Using AI to generate experiments</strong>
        <p>
          Paste <code>src/labs/COMPONENTS.md</code> into Claude, describe the
          experiment, and have it generate the full folder structure (aim,
          theory, apparatus, procedure, observations, conclusion, and circuit
          definition). Register the result in <code>semesters/catalog.ts</code>.
        </p>
      </Callout>

      <h2>Pages in this guide</h2>

      <ul>
        <li>
          <Link href="/docs/quickstart">Quickstart</Link> — add your first
          experiment in 5 minutes
        </li>
        <li>
          <Link href="/docs/video-tutorial">Video tutorial</Link> — watch a
          step-by-step walkthrough of adding an experiment
        </li>
        <li>
          <Link href="/docs/components">Component types</Link> — every
          renderable type and its props
        </li>
        <li>
          <Link href="/docs/geometry">Writing geometry</Link> — how to build a
          new Three.js component
        </li>
        <li>
          <Link href="/docs/registry">Registry &amp; renderer</Link> — how{" "}
          <code>COMPONENT_REGISTRY</code> works
        </li>
        <li>
          <Link href="/docs/circuits">Circuit schema</Link> — the full{" "}
          <code>Circuit</code> type
        </li>
        <li>
          <Link href="/docs/pins">Pin references</Link> — every{" "}
          <code>PinRef</code> variant explained
        </li>
        <li>
          <Link href="/docs/steps">Steps &amp; highlighting</Link> — authoring
          step-by-step assembly
        </li>
        <li>
          <Link href="/docs/columns">Column layout guide</Link> — placement
          rules for breadboard columns
        </li>
        <li>
          <Link href="/docs/types">TypeScript types</Link> — full type reference
        </li>
        <li>
          <Link href="/docs/constraints">Constraints &amp; rules</Link> — what
          the renderer expects
        </li>
      </ul>

      <DocNav>
        <span />
        <DocNavLink as={Link} href="/docs/quickstart" data-dir="next">
          Quickstart
        </DocNavLink>
      </DocNav>
    </Prose>
  );
}
