import { type SceneProcedureStep } from "@/labs/experiments/types";

export const step: SceneProcedureStep = {
  label: "Verify JK set",
  body: "Set J=1 and K=0 and apply an active clock edge. Q should become 1.",
  show: [
    "bb",
    "psu",
    "and_jclk",
    "nand_sbar",
    "and_kclk",
    "nand_rbar",
    "nand_q",
    "nand_qb",
    "w_qb_q",
    "w_q_qb",
    "w_j_and",
    "w_clk_andj",
    "w_k_and",
    "w_clk_andk",
    "w_andj_sbar",
    "w_qb_sbar",
    "w_andk_rbar",
    "w_q_rbar",
    "w_sbar_q",
    "w_rbar_qb",
    "r_q",
    "led_q",
    "r_qb",
    "led_qb",
    "w_q_led",
    "w_r_led_q",
    "w_qb_led",
    "w_r_led_qb",
    "w_gnd_q",
    "w_gnd_qb",
  ],
  highlight: "nand_q",
};
